### ISSUE TITLE
Error in mmkh(x, ci = 0.95) : Input data must be a vector

### ISSUE THREAD

**Issue by sang-thomte** [cran/modifiedmk#1]
Hello!
I recently installed the latest version of the modifiedmk package under R version 4.2.1. While trying the run the default functions using the default timeseries 'x' (annual nile riverflow data) provided, I am getting "Error in mmkh(x, ci = 0.95) : Input data must be a vector" message. I tried with my own ts data and I am still getting the same error message.  I tried an older version of the package (1.5.0) and I am getting the same error.

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by sang-thomte** [comment]
Apologies! Haven't really gotten the hang of things. Thank you for the prompt reminder.
